name: CustomParticle
version: ${project.version}
main: jp.abyss.spigot.plugin.customparticle.CustomParticle
api-version: 1.12.2
authors: [AbyssMembers]

commands:
  customparticle:
    aliases:
      - cp
    permission: CustomParticle.customparticle
  picture:
    permission: CustomParticle.picture
